### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by jamesqo** [Winescan/Prototype#21]
- [ ] 7/1 - Port the app to iOS
- [ ] 7/7 - Have the app calling into the Winescan API to load its data
- [ ] 7/14 - Finalize most of the design aspects of the app. Finish integrating with react-native-camera and have the scan functionality working.
...
- [ ] Early August - have a presentable version of the new app that can be given to users at summer wine fairs
