### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by jamesqo** [Winescan/Prototype#3]
- [ ] https://github.com/wix/react-native-navigation/issues/1798
- [ ] Consider switching from react-native-navigation to react-navigation: https://github.com/react-navigation/react-navigation/issues/4105#issuecomment-385996653
- [ ] Search screen
  - [ ] Pick good color for the menu on the search screen
  - [ ] Fix menu's vertical spacing
  - [ ] Fix empty space to left of search bar
    - Just replace it with a plain TextInput, or fork the code
- [ ] Redesign so that the images can fit into squares?
  - We need more panoramic images of each wine.
- [ ] Add a tiny bar atop each icon that will slide when the user taps on a new tab
- [ ] Remove stripes from scan icon bg
- [ ] The index.js code isn't actually being called
